//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Pggm.Components.Sample.Services
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Client 
    {
        #pragma warning disable 8618
        private string _baseUrl;
        #pragma warning restore 8618

        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings, true);
        private Newtonsoft.Json.JsonSerializerSettings _instanceSettings;

    #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public Client(System.Net.Http.HttpClient httpClient)
    #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            BaseUrl = "https://your-api-base-url";
            _httpClient = httpClient;
            Initialize();
        }

        private static Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings()
        {
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set
            {
                _baseUrl = value;
                if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
                    _baseUrl += '/';
            }
        }

        protected Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);

        partial void Initialize();

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// GetFacturen
        /// </summary>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Overzicht van facturen voor de gegeven factuurnummer en/of organisatienummer</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<FactuurLijst>> GetfacturenAsync(string factuurnummer, string organisatienummer, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History)
        {
            return GetfacturenAsync(factuurnummer, organisatienummer, pGGM_Message_ID, pGGM_Fondscode, pGGM_Correlation_ID, pGGM_Correlation_History, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// GetFacturen
        /// </summary>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Overzicht van facturen voor de gegeven factuurnummer en/of organisatienummer</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<FactuurLijst>> GetfacturenAsync(string factuurnummer, string organisatienummer, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (pGGM_Message_ID == null)
                        throw new System.ArgumentNullException("pGGM_Message_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Message-ID", ConvertToString(pGGM_Message_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Fondscode == null)
                        throw new System.ArgumentNullException("pGGM_Fondscode");
                    request_.Headers.TryAddWithoutValidation("PGGM-Fondscode", ConvertToString(pGGM_Fondscode, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_ID == null)
                        throw new System.ArgumentNullException("pGGM_Correlation_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Correlation-ID", ConvertToString(pGGM_Correlation_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_History != null)
                        request_.Headers.TryAddWithoutValidation("PGGM-Correlation-History", string.Join(",", pGGM_Correlation_History.Select(g => g.ToString())));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "facturen"
                    urlBuilder_.Append("facturen");
                    urlBuilder_.Append('?');
                    if (factuurnummer != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("factuurnummer")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(factuurnummer, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (organisatienummer != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("organisatienummer")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(organisatienummer, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<FactuurLijst>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 500)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("Er is een fout opgetreden in de applicatie", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// GetFacturenByInstantienummer
        /// </summary>
        /// <remarks>
        /// GetFacturenByInstantienummer
        /// </remarks>
        /// <param name="instantienummer">Format - int32. Nummer van de instantie binnen PGGM</param>
        /// <param name="begindatum">Format - date-time (as date-time in RFC3339). Datum vanaf wanneer facturen opgehaald moeten worden</param>
        /// <param name="einddatum">Format - date-time (as date-time in RFC3339). Datum tot wanneer facturen opgehaald moeten worden</param>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Overzicht van facturen voor de gegeven instantie van begindatum tot einddatum</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Factuur>> GetfacturenbyinstantienummerAsync(int instantienummer, System.DateTimeOffset? begindatum, System.DateTimeOffset? einddatum, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History)
        {
            return GetfacturenbyinstantienummerAsync(instantienummer, begindatum, einddatum, pGGM_Message_ID, pGGM_Fondscode, pGGM_Correlation_ID, pGGM_Correlation_History, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// GetFacturenByInstantienummer
        /// </summary>
        /// <remarks>
        /// GetFacturenByInstantienummer
        /// </remarks>
        /// <param name="instantienummer">Format - int32. Nummer van de instantie binnen PGGM</param>
        /// <param name="begindatum">Format - date-time (as date-time in RFC3339). Datum vanaf wanneer facturen opgehaald moeten worden</param>
        /// <param name="einddatum">Format - date-time (as date-time in RFC3339). Datum tot wanneer facturen opgehaald moeten worden</param>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Overzicht van facturen voor de gegeven instantie van begindatum tot einddatum</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Factuur>> GetfacturenbyinstantienummerAsync(int instantienummer, System.DateTimeOffset? begindatum, System.DateTimeOffset? einddatum, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History, System.Threading.CancellationToken cancellationToken)
        {
            if (instantienummer == null)
                throw new System.ArgumentNullException("instantienummer");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (pGGM_Message_ID == null)
                        throw new System.ArgumentNullException("pGGM_Message_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Message-ID", ConvertToString(pGGM_Message_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Fondscode == null)
                        throw new System.ArgumentNullException("pGGM_Fondscode");
                    request_.Headers.TryAddWithoutValidation("PGGM-Fondscode", ConvertToString(pGGM_Fondscode, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_ID == null)
                        throw new System.ArgumentNullException("pGGM_Correlation_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Correlation-ID", ConvertToString(pGGM_Correlation_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_History != null)
                        request_.Headers.TryAddWithoutValidation("PGGM-Correlation-History", string.Join(",", pGGM_Correlation_History.Select(g => g.ToString())));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "instanties/{instantienummer}/facturen"
                    urlBuilder_.Append("instanties/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(instantienummer, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/facturen");
                    urlBuilder_.Append('?');
                    if (begindatum != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("begindatum")).Append('=').Append(System.Uri.EscapeDataString(begindatum.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (einddatum != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("einddatum")).Append('=').Append(System.Uri.EscapeDataString(einddatum.Value.ToString("s", System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<Factuur>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 500)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("Er is een fout opgetreden in de applicatie", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Factuurspecificaties voor een instantie en factuur
        /// </summary>
        /// <remarks>
        /// GetFactuurSpecificaties
        /// </remarks>
        /// <param name="instantienummer">Format - int32. Nummer van de instantie binnen PGGM</param>
        /// <param name="factuurnummer">Factuurnummer van de factuur</param>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Een lijst factuurspecificaties</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Factuurspecificatie>> GetfactuurspecificatiesAsync(int instantienummer, string factuurnummer, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History)
        {
            return GetfactuurspecificatiesAsync(instantienummer, factuurnummer, pGGM_Message_ID, pGGM_Fondscode, pGGM_Correlation_ID, pGGM_Correlation_History, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Factuurspecificaties voor een instantie en factuur
        /// </summary>
        /// <remarks>
        /// GetFactuurSpecificaties
        /// </remarks>
        /// <param name="instantienummer">Format - int32. Nummer van de instantie binnen PGGM</param>
        /// <param name="factuurnummer">Factuurnummer van de factuur</param>
        /// <param name="pGGM_Message_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_ID">Format - guid.</param>
        /// <param name="pGGM_Correlation_History">Historie van Correlation Ids, in volgorde met de huidige als laatste</param>
        /// <returns>Een lijst factuurspecificaties</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Factuurspecificatie>> GetfactuurspecificatiesAsync(int instantienummer, string factuurnummer, System.Guid pGGM_Message_ID, string pGGM_Fondscode, System.Guid pGGM_Correlation_ID, System.Collections.Generic.IEnumerable<System.Guid> pGGM_Correlation_History, System.Threading.CancellationToken cancellationToken)
        {
            if (instantienummer == null)
                throw new System.ArgumentNullException("instantienummer");

            if (factuurnummer == null)
                throw new System.ArgumentNullException("factuurnummer");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (pGGM_Message_ID == null)
                        throw new System.ArgumentNullException("pGGM_Message_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Message-ID", ConvertToString(pGGM_Message_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Fondscode == null)
                        throw new System.ArgumentNullException("pGGM_Fondscode");
                    request_.Headers.TryAddWithoutValidation("PGGM-Fondscode", ConvertToString(pGGM_Fondscode, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_ID == null)
                        throw new System.ArgumentNullException("pGGM_Correlation_ID");
                    request_.Headers.TryAddWithoutValidation("PGGM-Correlation-ID", ConvertToString(pGGM_Correlation_ID, System.Globalization.CultureInfo.InvariantCulture));

                    if (pGGM_Correlation_History != null)
                        request_.Headers.TryAddWithoutValidation("PGGM-Correlation-History", string.Join(",", pGGM_Correlation_History.Select(g => g.ToString())));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "instanties/{instantienummer}/facturen/{factuurnummer}/specificaties"
                    urlBuilder_.Append("instanties/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(instantienummer, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/facturen/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(factuurnummer, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/specificaties");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<Factuurspecificatie>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 400)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("De aanvraag is ongeldig", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 401)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("Er is geen authenticatie informatie meegestuurd", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 403)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("De gebruiker heeft niet voldoende rechten", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 404)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("De opgevraagde entiteit is niet gevonden", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 500)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("Er is een fout opgetreden in de applicatie", status_, responseText_, headers_, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
    #else
            return content.ReadAsStringAsync();
    #endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
    #else
            return content.ReadAsStreamAsync();
    #endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false))
                    using (var streamReader = new System.IO.StreamReader(responseStream))
                    using (var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader))
                    {
                        var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
                        var typedBody = serializer.Deserialize<T>(jsonTextReader);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (Newtonsoft.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FactuurLijst
    {

        [Newtonsoft.Json.JsonProperty("index", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Index { get; set; }

        [Newtonsoft.Json.JsonProperty("instantienummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Instantienummer { get; set; }

        [Newtonsoft.Json.JsonProperty("instantienaam", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Instantienaam { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurstatus", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuurstatus { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurnummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuurnummer { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurdatum", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? Factuurdatum { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurbedrag", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal Factuurbedrag { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurtype", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuurtype { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurbron", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuurbron { get; set; }

        [Newtonsoft.Json.JsonProperty("organisatienummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Organisatienummer { get; set; }

        [Newtonsoft.Json.JsonProperty("factuuromschrijving", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuuromschrijving { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Factuur
    {

        [Newtonsoft.Json.JsonProperty("factuurnummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Factuurnummer { get; set; }

        [Newtonsoft.Json.JsonProperty("instantienummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Instantienummer { get; set; }

        [Newtonsoft.Json.JsonProperty("instantienaam", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Instantienaam { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurperiodeBegindatum", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset FactuurperiodeBegindatum { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurperiodeEinddatum", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset FactuurperiodeEinddatum { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurBedrag", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal FactuurBedrag { get; set; }

        [Newtonsoft.Json.JsonProperty("factuurdatum", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? Factuurdatum { get; set; }

        [Newtonsoft.Json.JsonProperty("vervaldatum", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? Vervaldatum { get; set; }

        [Newtonsoft.Json.JsonProperty("rekeningnummerIncasso", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RekeningnummerIncasso { get; set; }

        [Newtonsoft.Json.JsonProperty("loonheffingenNummer", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LoonheffingenNummer { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Factuurspecificatie
    {

        [Newtonsoft.Json.JsonProperty("index", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Index { get; set; }

        [Newtonsoft.Json.JsonProperty("instantienummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Instantienummer { get; set; }

        [Newtonsoft.Json.JsonProperty("periodiciteit", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Periodiciteit Periodiciteit { get; set; }

        [Newtonsoft.Json.JsonProperty("jaar", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Jaar { get; set; }

        [Newtonsoft.Json.JsonProperty("tijdvaknummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Tijdvaknummer { get; set; }

        [Newtonsoft.Json.JsonProperty("tijdvak", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Tijdvak { get; set; }

        [Newtonsoft.Json.JsonProperty("naam", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Naam { get; set; }

        [Newtonsoft.Json.JsonProperty("klantnummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Klantnummer { get; set; }

        [Newtonsoft.Json.JsonProperty("burgerservicenummer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Burgerservicenummer { get; set; }

        [Newtonsoft.Json.JsonProperty("begindatum", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset Begindatum { get; set; }

        [Newtonsoft.Json.JsonProperty("einddatum", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset Einddatum { get; set; }

        [Newtonsoft.Json.JsonProperty("nummer_inkomstenverhouding", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Nummer_inkomstenverhouding { get; set; }

        [Newtonsoft.Json.JsonProperty("salaris", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Salaris { get; set; }

        [Newtonsoft.Json.JsonProperty("onregelmatigheidstoeslag", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Onregelmatigheidstoeslag { get; set; }

        [Newtonsoft.Json.JsonProperty("verloonde_uren", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Verloonde_uren { get; set; }

        [Newtonsoft.Json.JsonProperty("deeltijdfactor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Deeltijdfactor { get; set; }

        [Newtonsoft.Json.JsonProperty("soort", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public SoortFacturering Soort { get; set; }

        [Newtonsoft.Json.JsonProperty("premiebasisregeling", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal Premiebasisregeling { get; set; }

        [Newtonsoft.Json.JsonProperty("permiewiaexcedent", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal Permiewiaexcedent { get; set; }

        [Newtonsoft.Json.JsonProperty("totaalpremie", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public decimal Totaalpremie { get; set; }

        [Newtonsoft.Json.JsonProperty("bijzonderheid", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Bijzonderheid { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Periodiciteit
    {

        [System.Runtime.Serialization.EnumMember(Value = @"JAARLIJKS")]
        JAARLIJKS = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"MAANDELIJKS")]
        MAANDELIJKS = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"VIERWEKELIJKS")]
        VIERWEKELIJKS = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum SoortFacturering
    {

        [System.Runtime.Serialization.EnumMember(Value = @"OPGELEGD")]
        OPGELEGD = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"TEGENGEBOEKT")]
        TEGENGEBOEKT = 1,

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765
