name: Deploy Blazor Sample to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly project
        run: dotnet publish Sample/Blazor.Pggm.Components.Sample.csproj -c Release -o release

      - name: Change base href in index.html
        run: |
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|' release/wwwroot/index.html

      - name: Add 404.html for GitHub Pages redirect
        run: |
          echo '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title></title>\n</head>\n<body>\n    <script>\n        sessionStorage.setItem("redirect", location.href);\n        location.replace("/${{ github.event.repository.name }}/");\n    </script>\n</body>\n</html>' > release/wwwroot/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
          force_orphan: true
